#!/usr/bin/env zsh
# Gemini CLI Installer
# Compiles the agentic framework into a single GEMINI.md for Gemini CLI
# Usage: ./installers/gemini-cli.sh [--target <dir>] [--agents all|<list>] [--skills all|<list>]

set -euo pipefail

# --- Configuration ---
SCRIPT_DIR="${0:A:h}"
FRAMEWORK_DIR="${SCRIPT_DIR:h}"
TARGET_DIR="${PWD}"
AGENTS="all"
SKILLS="all"
DRY_RUN=false
UPDATE_MODE=false

# --- Colors ---
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# --- Functions ---
info()  { echo "${BLUE}[INFO]${NC} $1" }
ok()    { echo "${GREEN}[OK]${NC} $1" }
warn()  { echo "${YELLOW}[WARN]${NC} $1" }
error() { echo "${RED}[ERROR]${NC} $1" >&2 }

usage() {
    cat <<EOF
Usage: $(basename "$0") [OPTIONS]

Compile agentic framework into a single GEMINI.md.

Options:
  --target <dir>      Target project directory (default: current directory)
  --agents <list>     Agents to include: "all" or comma-separated names (default: all)
  --skills <list>     Skills to include: "all" or comma-separated names (default: all)
  --update            Regenerate GEMINI.md without overwriting project config
  --dry-run           Show what would be done without making changes
  -h, --help          Show this help

Examples:
  $(basename "$0") --target ~/projects/my-app
  $(basename "$0") --agents analysis-expert,plan-expert,implement-expert
  $(basename "$0") --update
EOF
    exit 0
}

# --- Parse Arguments ---
while [[ $# -gt 0 ]]; do
    case "$1" in
        --target)  TARGET_DIR="$2"; shift 2 ;;
        --agents)  AGENTS="$2"; shift 2 ;;
        --skills)  SKILLS="$2"; shift 2 ;;
        --update)  UPDATE_MODE=true; shift ;;
        --dry-run) DRY_RUN=true; shift ;;
        -h|--help) usage ;;
        *) error "Unknown option: $1"; usage ;;
    esac
done

TARGET_DIR="${TARGET_DIR:A}"

# --- Validation ---
if [[ ! -d "$FRAMEWORK_DIR/agents" ]]; then
    error "Framework directory not found. Run from the agentic-framework root."
    exit 1
fi

if [[ ! -d "$TARGET_DIR" ]]; then
    error "Target directory does not exist: $TARGET_DIR"
    exit 1
fi

info "Target: $TARGET_DIR"
info "Agents: $AGENTS"
info "Skills: $SKILLS"
[[ "$DRY_RUN" == true ]] && warn "DRY RUN — no files will be created"

# --- Get lists ---
get_agents_list() {
    if [[ "$AGENTS" == "all" ]]; then
        find "$FRAMEWORK_DIR/agents" -name "*.agent.md" ! -name "_template*" -exec basename {} .agent.md \;
    else
        echo "${AGENTS//,/$'\n'}"
    fi
}

get_skills_list() {
    if [[ "$SKILLS" == "all" ]]; then
        find "$FRAMEWORK_DIR/skills" -mindepth 1 -maxdepth 1 -type d ! -name "_template" -exec basename {} \;
    else
        echo "${SKILLS//,/$'\n'}"
    fi
}

# --- Generate GEMINI.md ---
generate_gemini_md() {
    cat <<'HEADER'
# Project Instructions for Gemini

> Auto-generated by agentic-framework installer. Edit `.ai-framework/config/project.md` for project-specific settings.

HEADER

    # --- Core Principles (compact) ---
    cat <<'CORE'
## Core Principles

You operate under **System 2 (Slow Thinking)** — Precision, Minimalism, Safety.

### YAGNI (You Aren't Gonna Need It)
- Build ONLY what's asked. No speculative features, unrequested abstractions, or "while I'm here" improvements.
- Before adding anything: Can I achieve this by deleting code or reusing an existing function?
- No new packages unless standard library is impossible.

### Anti-Hallucination
- Only reference code/APIs you have verified exist in the actual codebase.
- Read files before editing. If you can't quote 3 lines of context around your edit, you haven't read the file.
- Never present unverified claims as facts. Cite file:line or mark as "unverified."

### Security (Always Active)
- Assume production if environment unknown. No destructive operations without confirmation.
- Never hardcode secrets. Use parameterized queries. Validate inputs at system boundaries.
- Apply OWASP Top 10 awareness to all code suggestions.

CORE

    # --- Task Classification (compact) ---
    cat <<'TIERS'

## Task Classification

| Tier | Criteria | Response |
|------|----------|----------|
| 0 | No code changes, trivial | Execute directly |
| 1 | Single-file, minor changes | Brief checkpoint, then implement |
| 2 | Multi-file, business logic, new components | Checkpoint + Design Considerations |
| 3 | Architecture, new features, cross-service | Checkpoint + ADR |

**Rule**: When in doubt, choose the HIGHER tier.

### Checkpoint (Tier 1+)
Before implementing, briefly state: What did you read? What's the critical insight? What's the YAGNI check?

TIERS

    # --- Agents (compact) ---
    echo ""
    echo "## Agents"
    echo ""
    echo "When a request matches an agent's domain, adopt that agent's methodology:"
    echo ""

    get_agents_list | sort | while read -r agent; do
        if [[ -f "$FRAMEWORK_DIR/agents/${agent}.agent.md" ]]; then
            local title=$(grep "^# " "$FRAMEWORK_DIR/agents/${agent}.agent.md" | head -1 | sed 's/^# //')
            local constraint=$(grep -A1 "Core Constraint" "$FRAMEWORK_DIR/agents/${agent}.agent.md" | tail -1 | sed 's/.*⛔ //' | sed 's/—.*//' | tr -d '*>')
            local mission=$(sed -n '/^## Core Mission/,/^##/{/^## Core Mission/d; /^##/d; p;}' "$FRAMEWORK_DIR/agents/${agent}.agent.md" | head -2 | tr '\n' ' ')

            echo "### ${title:-$agent}"
            [[ -n "$constraint" ]] && echo "**Constraint**: ${constraint}"
            echo "${mission:-See agent definition for details.}"
            echo ""
        fi
    done

    # --- Skills (compact, merged by theme) ---
    cat <<'SKILLS_HEADER'

## Skills (Applied Contextually)

### Always Active
- **Anti-Hallucination**: Verify all code references. Read before edit. Cite or caveat.
- **Green Coding**: Efficient data structures, minimize allocations, async for I/O, cache stable data.

### Analysis & Reasoning
- **Transparent Reasoning**: For Tier 2+ decisions — document options, criteria, trade-offs.
- **Exhaustive Analysis**: When completeness matters — batch process, track progress, verify 100% coverage.
- **White-Box Tracing**: Trace control flow, data flow, program slicing for verification.

### Testing & Quality
- **Test Case Design**: EP, BVA, decision tables, state transitions, pairwise. Traceability to requirements.
- **PR Diff Analyzer**: Parse diffs into structured data for review.

### Workflow
- **Error Handling**: Retry with backoff, fallback degradation, self-correction protocol.
- **Multi-Agent Orchestration**: Pipeline, Router, Orchestrator-Worker, Best-of-N patterns.
- **Document Consolidation**: 7-phase merge process for multiple sources into SSOT.
- **Workspace Search**: Variation-aware search — generate term alternatives, try multiple tools.

SKILLS_HEADER

    # --- Output Conventions (compact) ---
    cat <<'OUTPUT'

## Output Conventions

Save analysis/plan/spec artifacts to `Local_Specification/`:
- Pattern: `Local_Specification/[TYPE]-[YYYYMMDD]-[slug].md`
- Types: ANALYSIS, PLAN, SPEC, RCA, FIX, TC, EXPLAIN, SECURITY
- With work item: `Local_Specification/[WORKITEM_TYPE]_[NUMBER]/[file].md`
- Code changes: make directly to source files (never use create_file for .ts/.cs/.py)

OUTPUT

    # --- Project Configuration ---
    echo ""
    echo "## Project Configuration"
    echo ""
    local config_file="$TARGET_DIR/.ai-framework/config/project.md"
    if [[ -f "$config_file" ]]; then
        # Include actual project config (skip the header comment)
        sed -n '/^## Organization/,$p' "$config_file"
    else
        echo "See \`.ai-framework/config/project.md\` for project-specific settings."
    fi
}

# --- Deploy ---
# Create config dir
if [[ "$DRY_RUN" != true ]]; then
    mkdir -p "$TARGET_DIR/.ai-framework/config"
fi

# Deploy project config (never overwrite)
local config_dst="$TARGET_DIR/.ai-framework/config/project.md"
if [[ -f "$config_dst" ]]; then
    warn "Project config exists — preserved"
else
    if [[ "$DRY_RUN" == true ]]; then
        echo "  [dry-run] $config_dst"
    else
        cp "$FRAMEWORK_DIR/config/project.template.md" "$config_dst"
        ok "Project config template deployed"
    fi
fi

# Generate GEMINI.md
info "Generating GEMINI.md..."
if [[ "$DRY_RUN" == true ]]; then
    echo "  [dry-run] $TARGET_DIR/GEMINI.md"
    echo "  [dry-run] Would contain $(generate_gemini_md | wc -l | tr -d ' ') lines"
else
    generate_gemini_md > "$TARGET_DIR/GEMINI.md"
    local line_count=$(wc -l < "$TARGET_DIR/GEMINI.md" | tr -d ' ')
    ok "GEMINI.md generated (${line_count} lines)"
    if [[ $line_count -gt 800 ]]; then
        warn "GEMINI.md exceeds 800 lines ($line_count). Consider reducing agents/skills."
    fi
fi

# --- Summary ---
echo ""
echo "════════════════════════════════════════════════════════════"
ok "Gemini CLI framework deployed to: $TARGET_DIR"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "Next steps:"
echo "  1. Edit .ai-framework/config/project.md with your project details"
echo "  2. Review GEMINI.md and customize as needed"
echo "  3. Gemini CLI will automatically read GEMINI.md from project root"
echo ""
echo "Structure created:"
echo "  $TARGET_DIR/"
echo "  ├── GEMINI.md          (single compiled file)"
echo "  └── .ai-framework/"
echo "      └── config/project.md"
